import Head from 'next/head';
import Navbar from './Navbar';
import { Cairo } from 'next/font/google';

const cairo = Cairo({ subsets: ['latin'] });

export default function Layout({ children, title }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>{title + ' - Torche Education Blog'}</title>
      </Head>
      <main className={cairo.className}>
        <Navbar />
        {children}
      </main>
    </>
  )
}